### ISSUE TITLE
Line chart: labels_x_last option

### ISSUE THREAD

**Issue by pjrundle** [bhallstein/BoggleChart#6]
BOOL: prevent the last x label (counterpart to labels-x-origin)

**Comment by bhallstein** [comment]
Could potentially achieve the same functionality w/ a `category_labels` function, but agree it would be easier as an option.

**Comment by bhallstein** [comment]
Implemented as labels_x_right_axis, since it isn't necessary the "last" label, if there aren't enough labels to cross the entire x axis.
